[UFC-825] subpath support
mendix/DeeplinkModule pull request #57
Opened 2023-08-28 09:32 UTC by WimJongeneel

2023-08-30 11:40 UTC, Robinfr requested changes
Only 1 comment.

2023-08-30 11:40 UTC, Robinfr commented on src/DeepLinkModule/javasource/deeplink/implementation/handler/ResponseHandler.java
> +			}
There's a random tab here I think?

2023-09-08 13:35 UTC, Robinfr approved these changes

2023-09-08 13:36 UTC, merged

2023-09-18 12:58 UTC, wegiswes commented
Hi, 

It looks like IMxRuntimeRequest.getRootUrl() is introduced in Mx10 so running the latest version of this module (10.0.4) in Mx9 results in a java compile error. Please update the required mx version in the marketplace accordingly 😇

2023-09-18 13:31 UTC, Robinfr commented
@wegiswes As the docs mention, DeepLink 10 is meant to be used with Mx10+. Please use DeepLink 9 for Mx9.